Revert "Support validating buffer usage with usage validation mode"
This reverts commit 1f3f5df6810adfd8c37ce25fb3c22c92a4e9bf02.

Reason for revert: blocks rolling into Chromium
https://chromium-review.googlesource.com/c/chromium/src/+/5841338
https://ci.chromium.org/ui/p/chromium/builders/try/dawn-mac-arm64-deps-rel/8457/overview
[ RUN      ] InternalStorageBufferBindingTests.QueryResolveBufferBoundAsInternalStorageBuffer/Metal_Apple_M2
Error: Assertion failure at ../../third_party/dawn/src/dawn/native/CommandEncoder.cpp:1128 (BeginComputePass): device->IsLockedByCurrentThreadIfNeeded()

Original change's description:
> Support validating buffer usage with usage validation mode
>
> This patch adds `UsageValidationMode` as the third parameter of
> `ValidateCanUseAs` with a buffer as input to align with the
> format of the function `ValidateCanUseAs` with a texture as input.
>
> This patch also updates the test `InternalStorageBufferBindingTests`
> by using classes in `native::` instead of the `wgpu::` to better
> test the `internal usage` of the buffers.
>
> Bug: chromium:42240463
> Test: dawn_unittests
> Change-Id: I2db2c922555ded050949da20828be17c95499152
> Reviewed-on: https://dawn-review.googlesource.com/c/dawn/+/204914
> Commit-Queue: Jiawei Shao <jiawei.shao@intel.com>
> Reviewed-by: Corentin Wallez <cwallez@chromium.org>

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: chromium:42240463
Change-Id: I87fd848faba5d6515edaba32c25b7537e2ef81f0
Reviewed-on: https://dawn-review.googlesource.com/c/dawn/+/205994
Auto-Submit: Yuly Novikov <ynovikov@chromium.org>
Reviewed-by: Jiawei Shao <jiawei.shao@intel.com>
Commit-Queue: Jiawei Shao <jiawei.shao@intel.com>
Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>