Fix missing <cstdint> include in TypedInteger.h
I wasn't able to build Dawn on Ubuntu 25.04 w/ GCC 14.2.0 because of the following error:
```
In file included from /tmp/dawn-20250829.192131/src/dawn/common/ityp_array.h:36,
                 from /tmp/dawn-20250829.192131/out/Debug/gen/src/dawn/native/ObjectType_autogen.h:5,
                 from /tmp/dawn-20250829.192131/out/Debug/gen/src/dawn/native/ObjectType_autogen.cpp:2:
/tmp/dawn-20250829.192131/src/dawn/common/TypedInteger.h: In constructor ‘constexpr dawn::detail::TypedIntegerImpl<Tag, T>::TypedIntegerImpl(I)’:
/tmp/dawn-20250829.192131/src/dawn/common/TypedInteger.h:103:35: error: ‘uint64_t’ does not name a type
  103 |         static_assert(static_cast<uint64_t>(std::numeric_limits<I>::max()) <=
      |                                   ^~~~~~~~
/tmp/dawn-20250829.192131/src/dawn/common/TypedInteger.h:40:1: note: ‘uint64_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
```

Adding the missing include fixes the issue.

This is an imported pull request from
https://github.com/google/dawn/pull/44

GITHUB_PR_HEAD_SHA=fd9577699a45b36d64b4ea1eb645d3e181bfb613
ORIGINAL_AUTHOR=Efflam <92077690+e2fo2l@users.noreply.github.com>
GitOrigin-RevId: d84bef0232f51d05aa85b5b3f706360dc8866f32
Change-Id: Ie895a4b270cc9bf21fadae1b8534cc86be4e32bd
Reviewed-on: https://dawn-review.googlesource.com/c/dawn/+/260116
Reviewed-by: Corentin Wallez <cwallez@chromium.org>
Commit-Queue: dan sinclair <dsinclair@chromium.org>
Reviewed-by: dan sinclair <dsinclair@chromium.org>