Roll Depot Tools from 95155bece7c2 to 20ce2373ddbe (58 revisions)
https://chromium.googlesource.com/chromium/tools/depot_tools.git/+log/95155bece7c2..20ce2373ddbe

2025-09-04 rop@google.com Fix: Use f-string for validation warning message.
2025-09-04 rop@google.com Checking for package managers in vuln sufficiency.
2025-09-04 ukai@google.com siso: add .sisorc support
2025-09-04 ayatane@chromium.org auth: Refactor missing access_token logic
2025-09-04 ukai@google.com ninja: fix TypeError: check_out_dir() missing 1 required positional argument
2025-09-03 ayatane@chromium.org auth: Remove unused param
2025-09-03 ayatane@chromium.org auth: Hoist exception handling in GerritAuthenticator
2025-09-03 ayatane@chromium.org auth: Disable ReAuth for git-credential-luci in depot_tools
2025-09-03 qjw@chromium.org roll git-credential-luci to improve error messaging
2025-09-03 qjw@chromium.org roll luci-auth-ssh-helper to support ping/pong check
2025-09-02 ukai@google.com autoninja: support running from outside of workspace
2025-09-02 recipe-mega-autoroller@chops-service-accounts.iam.gserviceaccount.com Roll recipe dependencies (trivial).
2025-09-02 recipe-mega-autoroller@chops-service-accounts.iam.gserviceaccount.com Roll recipe dependencies (trivial).
2025-09-02 rop@google.com Improving vuln scan sufficiency heuristics
2025-09-01 recipe-mega-autoroller@chops-service-accounts.iam.gserviceaccount.com Roll recipe dependencies (trivial).
2025-09-01 rop@google.com Changing CPE/Version to Warning
2025-08-30 recipe-mega-autoroller@chops-service-accounts.iam.gserviceaccount.com Roll recipe dependencies (trivial).
2025-08-29 rop@google.com Add validation for CPEPrefix and Version fields.
2025-08-29 qjw@chromium.org Roll git-credential-luci to default enable ReAuth
2025-08-29 recipe-mega-autoroller@chops-service-accounts.iam.gserviceaccount.com Roll recipe dependencies (trivial).
2025-08-29 msta@google.com Make `git cl presubmit` pass before running `git cl upload`.
2025-08-28 recipe-mega-autoroller@chops-service-accounts.iam.gserviceaccount.com Roll recipe dependencies (trivial).
2025-08-28 recipe-mega-autoroller@chops-service-accounts.iam.gserviceaccount.com Roll recipe dependencies (trivial).
2025-08-28 recipe-mega-autoroller@chops-service-accounts.iam.gserviceaccount.com Roll recipe dependencies (trivial).
2025-08-27 sshrimp@google.com Fix docstrings and add support for arbitrary CL try-results
2025-08-27 recipe-mega-autoroller@chops-service-accounts.iam.gserviceaccount.com Roll recipe dependencies (trivial).
2025-08-27 recipe-mega-autoroller@chops-service-accounts.iam.gserviceaccount.com Roll recipe dependencies (trivial).
2025-08-26 gbeaty@chromium.org Correctly accumulate gs upload URLs
2025-08-26 rgw@google.com [lucicfg] Update v1.45.7 -> 1.45.8
2025-08-25 msta@google.com Fix clang-format to work when you're not in a chromium checkout.
2025-08-25 tikuta@chromium.org recipes: Remove unnecessary annotations
2025-08-22 recipe-mega-autoroller@chops-service-accounts.iam.gserviceaccount.com Roll recipe dependencies (trivial).
2025-08-22 kalutes@google.com Add sqlparse to .vpython3
2025-08-22 ricea@chromium.org Revert "Roll git-credential-luci: enable ReAuth by default"
2025-08-21 no-reply@google.com repo: Update from upstream
2025-08-21 jiesheng@google.com Refactors the GCS dependency handling to unify the check for Cog
2025-08-21 qjw@chromium.org Roll git-credential-luci: enable ReAuth by default
2025-08-21 qjw@chromium.org Roll luci-auth-ssh-plugin
2025-08-21 jwata@google.com recipes: Set GCS URLs to output properties
2025-08-20 ayatane@chromium.org [auth] Close stdin for git-credential-luci
2025-08-20 recipe-mega-autoroller@chops-service-accounts.iam.gserviceaccount.com Roll recipe dependencies (trivial).
2025-08-20 qjw@chromium.org add luci-auth-ssh-* entrypoints
2025-08-20 qjw@chromium.org roll luci-auth-ssh* to support TCP port forwarding
2025-08-19 bpastene@chromium.org Uncap max line length for *.star files
2025-08-18 ddoman@chromium.org presubmit: add bypass-check-license instruction in the failure message
2025-08-18 qjw@chromium.org luci-auth-fido2-plugin: add a --list-devices flag for troubleshooting
2025-08-15 ddoman@chromium.org Reland "presubmit: emit errors instead of warnings for bad copyright headers"
2025-08-15 recipe-mega-autoroller@chops-service-accounts.iam.gserviceaccount.com Roll recipe dependencies (trivial).
2025-08-14 ddoman@chromium.org Revert "presubmit: emit errors instead of warnings for bad copyright headers"
2025-08-14 bsheedy@chromium.org Add presubmit checks for mcp/
2025-08-14 ddoman@chromium.org presubmit: emit errors instead of warnings for bad copyright headers
2025-08-14 bryner@google.com Use gclient_utils.rmtree() when updating a GCS dep to handle readonly files on Windows.
2025-08-14 recipe-mega-autoroller@chops-service-accounts.iam.gserviceaccount.com Roll recipe dependencies (trivial).
2025-08-14 sshrimp@google.com Add bsheedy to mcp/OWNERS
2025-08-14 bsheedy@chromium.org Deduplicate mcp/ prpc calls
2025-08-13 qjw@chromium.org luci-auth-fido2-plugin: use WindowsClient if available
2025-08-13 recipe-mega-autoroller@chops-service-accounts.iam.gserviceaccount.com Roll recipe dependencies (trivial).
2025-08-13 sshrimp@google.com Add git cl tools to mcp server

If this roll has caused a breakage, revert this CL and stop the roller
using the controls here:
https://autoroll.skia.org/r/depot-tools-dawn
Please CC dsinclair@google.com,webgpu-developers@google.com on the revert to ensure that a human
is aware of the problem.

To file a bug in Dawn: https://bugs.chromium.org/p/dawn/issues/entry

To report a problem with the AutoRoller itself, please file a bug:
https://issues.skia.org/issues/new?component=1389291&template=1850622

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md

Bug: None
Tbr: dsinclair@google.com
Change-Id: I1e78649b38773be314c95a6b834a18973d99ccbc
Reviewed-on: https://dawn-review.googlesource.com/c/dawn/+/260714
Commit-Queue: Dawn Autoroller <dawn-autoroll@skia-public.iam.gserviceaccount.com>
Bot-Commit: Dawn Autoroller <dawn-autoroll@skia-public.iam.gserviceaccount.com>