Revert "Improve DX compiler library loading"
This reverts commit e4d4669d79501b1acdd2bf017ba491b611d741da.

Reason for revert: asserts on Win x86
https://ci.chromium.org/ui/p/chromium/builders/try/dawn-win10-x86-deps-rel/53380/overview
https://chromium-swarm.appspot.com/task?id=6fe7c15bdfd81c10
Error: Assertion failure at ..\..\third_party\dawn\src\dawn\native\d3d12\PhysicalDeviceD3D12.cpp:573 (SetupBackendAdapterToggles): !GetBackend()->IsDXCAvailable()

Original change's description:
> Improve DX compiler library loading
>
> Previously, DX compiler DLLs were loaded using LoadLibrary with no path.
> D3D12 compiler DLLs were further sourced from the local user's SDK
> directory as a fallback.
>
> For better security, load DX compiler DLLs using full paths, with
> SEARCH_DLL_LOAD_DIR | SEARCH_DEFAULT_DIRS for better security. Scenarios
> such as Skia and x86 builds where we need dawn_use_built_dxc will
> fallback to FXC. No fallbacks to local user SDK directories.
>
> Bug:356665092
> Change-Id: Ib4148f9b89da694e3868b4f3c3c329a4b06ce922
> Reviewed-on: https://dawn-review.googlesource.com/c/dawn/+/229754
> Reviewed-by: Corentin Wallez <cwallez@chromium.org>
> Commit-Queue: Rafael Cintron <rafael.cintron@microsoft.com>
> Reviewed-by: Antonio Maiorano <amaiorano@google.com>

TBR=cwallez@chromium.org,rafael.cintron@microsoft.com,amaiorano@google.com,dawn-scoped@luci-project-accounts.iam.gserviceaccount.com

Bug: 356665092
Change-Id: Iaa97c4a036f84c0d5ee644b65280c56faa18c5ef
Reviewed-on: https://dawn-review.googlesource.com/c/dawn/+/233034
Reviewed-by: James Price <jrprice@google.com>
Commit-Queue: Yuly Novikov <ynovikov@chromium.org>