Removed Clang-specific pragmas to build with VS2019
When building for Windows with VS2019 (using 'is_clang=false') with the
default "warnings as errors" this occurs multiple times, halting the
build:

../../third_party/tint/samples/main.cc(88): error C2220:
the following warning is treated as an error

../../third_party/tint/samples/main.cc(88): warning C4068:
unknown pragma 'clang'

Since there's no shared macro for marking potential unused params the
simplest route of a (void) cast is chosen.

Bug: dawn:602
Change-Id: I4e6316df97dc3cd7e45260e2f7471cdd5a9b4b94
Reviewed-on: https://dawn-review.googlesource.com/c/tint/+/37700
Commit-Queue: dan sinclair <dsinclair@chromium.org>
Reviewed-by: dan sinclair <dsinclair@chromium.org>